server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/smartcampus
spring.datasource.username=ybenayed
spring.datasource.password=ybenayed

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true